version: '3.8'

services:
  webapp:
    build: .
    container_name: orbwatch
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    network_mode: "host"
